### ISSUE TITLE
Please update the plugin to work with the latest Discord update

### ISSUE THREAD

**Issue by Yazeed-Alshehri** [Sploric/MentionChannels#13]
This plugin is so terribly useful

**Comment by Sploric** [comment]
![image](https://user-images.githubusercontent.com/44213317/204703563-dc1bb1aa-d293-4d19-aaa5-f3fcf82fc0eb.png)
Not sure what version you are on, I am currently on stable 161255, with BD v1.8.2 (BD Version is very important, make sure you have that updated, which you can find [here](https://betterdiscord.app))

**Comment by Sploric** [comment]
Gonna close this seeing as I have yet to receive a response from you
