### ISSUE TITLE
plugin broken 

### ISSUE THREAD

**Issue by moosje2003** [Sploric/MentionChannels#14]
meta not found error
im on discord version Stable 165485 (07d8b41)
![image](https://user-images.githubusercontent.com/61630365/210347910-b36458ad-b445-4386-b479-4f342df390e7.png)
[error code.txt](https://github.com/Sploric/MentionChannels/files/10336166/error.code.txt)

**Comment by Sploric** [comment]
what version of the plugin did you download? It may help to upload your `MentionChannels.plugin.js` file here so I can inspect it.

**Comment by moosje2003** [comment]
here you go
[MentionChannels.plugin.zip](https://github.com/Sploric/MentionChannels/files/10340150/MentionChannels.plugin.zip)
i downloaded the one from you're github

**Comment by moosje2003** [comment]
it is still broken

**Comment by Sploric** [comment]
Assuming you fixed it- as you closed the issue

But incase you didn't, the files you uploaded that were supposed to be your plugin files are a file containing the html data for the website... which is not what you're supposed to upload.  You are supposed to download [this](https://raw.githubusercontent.com/Sploric/MentionChannels/main/MentionChannels.plugin.js) from the github [here](https://github.com/Sploric/MentionChannels/blob/main/MentionChannels.plugin.js)

**Comment by moosje2003** [comment]
yeah i alt clicked on the link i forgot that that just downloads the page
